# Generated by Django 4.2.2 on 2023-08-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombres'),
        ),
    ]
